### ISSUE TITLE
Shibalike Auth::user() not being set

### ISSUE THREAD

**Issue by james-daily** [razorbacks/laravel-shibboleth#7]
I'm starting from a new Laravel 5.4 project.  I've followed the README instructions, set up Shibalike, and added 

```
@if (Auth::guest())
    <a href="/shibboleth-login">Login</a>
@else
    <a href="/shibboleth-logout">
        Logout {{ Auth::user()->name }}
    </a>
@endif
```
to the default Laravel welcome page.  The login link works: I get directed to the basic Shibalike login page.  Usernames not listed in `shibboleth.php` are correctly rejected, as are login attempts where the username and password do not match.  Correct logins get redirected to the home page, but `Auth::guest()` is always true, and I'm also not seeing any user information in `$_SERVER`.

I can attach copies of my configuration files if that would help.

**Comment by jpuck** [comment]
Those appear to be the routes for shibboleth, not shibalike, so I'm a little surprised it loaded that view at all. It should be `/emulated/login` and `/emulated/logout` but I haven't used shibalike much. Have you been able to load with a real shibboleth idp? If you have a repository you can link to, then I'd be happy to take a look.

**Comment by james-daily** [comment]
The links end up redirected to `https://[hostname]/emulated/idp` whether I use `/shibboleth-login` or `/emulated/login`.  

`emulate_idp` is set to `true` in `shibboleth.php`.  

`add_new_users` is also set to `true`, but new users aren't appearing in the users table, either.

Perhaps notably, only the 'admin', 'staff', and 'user' users authenticate (or at least get redirected back to the home page).  This is true even if I remove those users or replace them in `shibboleth.php`.   This suggests to me that something isn't being read properly.

We have a real Shibboleth IdP, but we haven't tried to integrate with it yet.  This is just getting the barest bones of an environment setup on a development workstation.

**Comment by james-daily** [comment]
`ShibbolethControler->emulateIdp()` lacks the user creation and Laravel authentication steps that `idpAuthenticate()` contains.  I added the following to `emulatedIdp()`:

```
            $userAttrs = $this->idp->fetchAttrs($username);
            if ($userAttrs) {

                $userClass = config('auth.providers.users.model', 'App\User');

                // Attempt to login with the email, if success, update the user model
                // with data from the Shibboleth headers (if present)
                if (Auth::attempt(array('email' => $userAttrs['email']), true)) {
                    $user = $userClass::where('email', '=', $userAttrs['email'])->first();

                    // Update the model as necessary
                    $user->update($userAttrs);
                }

                // Add user and send through auth.
                elseif (config('shibboleth.add_new_users', true)) {
                    $userAttrs['password'] = 'shibboleth';
                    $user = $userClass::create($userAttrs);
                    Auth::login($user);
                }
```

Doing so gives me a valid `Auth::user()` for the duration of that method, but it doesn't persist through the redirect back to the home page.

**Comment by jpuck** [comment]
Hi James,

I have made a new release 2.2.3 which fixes a number of things in order to work with Shibalike.

    composer update razorbacks/laravel-shibboleth

I'm sorry I don't ever use Shibalike, just Shibboleth proper, so I never put any diligence into maintenance - it's just been leftover for legacy support. Here's [an example project][1] you can clone to demonstrate Shibalike's working functionality.

[1]:https://github.com/MyTeamName/laravel-shibalike/commit/ca153c42c7aaf1915c7bd62426e1125f702b8939

**Comment by james-daily** [comment]
Thanks!  I'll give that a try.  I appreciate it!
